//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_cobros.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sistema_de_cobros.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check20 {
            get {
                object obj = ResourceManager.GetObject("check20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete25 {
            get {
                object obj = ResourceManager.GetObject("delete25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo_de_Cevenca {
            get {
                object obj = ResourceManager.GetObject("Logo_de_Cevenca", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Title of the document&lt;/title&gt;
        ///    &lt;style&gt;
        ///        table.border {
        ///            border-collapse: collapse;
        ///        }
        ///
        ///            table.border th {
        ///                padding: 5px;
        ///                border: 1px solid black;
        ///            }
        ///
        ///            table.border td {
        ///                padding: 5px;
        ///                border: 1px solid black;
        ///            }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;table style=&quot;width:100%&quot;&gt;
        ///        [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Plantilla {
            get {
                return ResourceManager.GetString("Plantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///  &lt;title&gt;REPORTE DIARIO&lt;/title&gt;
        ///  &lt;style&gt;
        ///    body {
        ///      font-family: Arial, sans-serif;
        ///      background-color: #f9f9f9;
        ///      margin: 0;
        ///      padding: 20px;
        ///      color: #333;
        ///    }
        ///    .container {
        ///      max-width: 400px;
        ///      margin: 0 auto;
        ///      background: #fff;
        ///      padding: 15px 20px;
        ///      border: 1px solid #ccc;
        ///      box-shadow: 0 0 5px rgba(0,0,0,0.2);
        ///    }
        ///    /* Encabezado */ [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Plantilla_Reporte {
            get {
                return ResourceManager.GetString("Plantilla_Reporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///  &lt;title&gt;Recibo&lt;/title&gt;
        ///  &lt;style&gt;
        ///    body {
        ///      font-family: Arial, sans-serif;
        ///      background-color: #f9f9f9;
        ///      margin: 0;
        ///      padding: 20px;
        ///      color: #333;
        ///    }
        ///    .container {
        ///      max-width: 400px;
        ///      margin: 0 auto;
        ///      background: #fff;
        ///      padding: 15px 20px;
        ///      border: 1px solid #ccc;
        ///      box-shadow: 0 0 5px rgba(0,0,0,0.2);
        ///    }
        ///    /* Encabezado */
        ///    .h [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Plantilla2 {
            get {
                return ResourceManager.GetString("Plantilla2", resourceCulture);
            }
        }
    }
}
